package com.chat.component;

import java.io.FileOutputStream;
import javax.swing.JFileChooser;

public class rcvFile extends javax.swing.JLayeredPane {

    public rcvFile() {
        initComponents();
    }

    private byte[] data;

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    private String fileName;
    private String fileSize;

    public void set(String fileName) {
        this.fileName = fileName.split("!")[0];
        this.fileSize = fileName.split("!")[1];
        txt.setText(this.fileName);
        txt.setToolTipText(fileSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new com.chat.component.Chat_Text();
        user = new javax.swing.JLabel();

        txt.setEditable(false);
        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(6, 23, 183));
        txt.setBgColor(new java.awt.Color(222, 221, 255));
        txt.setBorderColor(new java.awt.Color(6, 23, 183));
        txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMouseClicked(evt);
            }
        });

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chat/icon/user.png"))); // NOI18N

        setLayer(txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(user, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMouseClicked
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser();
        int c = ch.showSaveDialog(null);
        if (c == JFileChooser.APPROVE_OPTION) {
            try {
                FileOutputStream out = new FileOutputStream(ch.getSelectedFile());
                out.write(getData());
                out.close();
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.chat.component.Chat_Text txt;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
